const number1 = 5;
const number2 = 7;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 6;
const payment = 10;
const amountRemaining = payment - charge;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const tests = 98;
const assignments = 86;
const final = 78;
const grade = (tests + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Kenza ';
const lastName = ' Tazi';
const fullName = firstName + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 3;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 280;
const isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT!';
console.log(nickname);
console.log(typeof nickname);
